version: 2

updates:
- package-ecosystem: "composer"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
  target-branch: "develop"
  commit-message:
    prefix: "chore(deps)"
  versioning-strategy: "auto"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
  commit-message:
    prefix: "chore(deps)"
